# Dependencies
markdown:	redcarpet
pygments:	true

# Permalinks
permalink:	/blog/:title

# Setup
title:		Jonas Gebhardt's Notes
tagline:	'People + Design + Technology'
description:	'A blog.'
url:		http://jonasgebhardt.com

author:
  name:		'Jonas Gebhardt'
  url:		https://twitter.com/jonasgebhardt

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/jonasgebhardt
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/jgebhardt
    desc:	My projects on github

  - icon:	facebook-alt
    url:	https://facebook.com/jonas.gebhardt
    desc:	Follow me on Facebook

  - icon: instagram
    url:  https://instagram.com/jxg
    desc: Follow me on Instagram


menu:
  - title:	Home
    url:	/

copyright:
  author:	Jonas Gebhardt
  url:		http://jonasgebhardt.com
  type_title:	'Theme: Thinny 2.1 by Camporez'
  type_url:	https://github.com/camporez/Thinny
